/**
 * ShareExport — copy the current session summary to the clipboard as text.
 *
 * Builds a small plain-text summary from the live `buddhaStatus` payload and
 * writes it to navigator.clipboard, with graceful fallback to a hidden
 * textarea + document.execCommand('copy') on browsers without the async
 * Clipboard API. Shows a brief AntD toast on success / failure.
 *
 * @component
 */
import React, { useCallback } from 'react';
import { Card, Button, Typography, Space } from 'antd';
import { Share2, ClipboardCopy, Check } from 'lucide-react';
import type { RecitationStatus } from '../../../types';
import { useUIStore } from '../../stores/uiStore';

const { Text, Title } = Typography;

interface ShareExportProps {
  /** The live recitation status from useWebSocketStable. */
  buddhaStatus?: RecitationStatus | null;
  /** Current intention text to include in the export. */
  intention?: string;
}

interface BuildSummaryArgs {
  buddhaStatus?: RecitationStatus | null;
  intention?: string;
}

function buildSummary({ buddhaStatus, intention }: BuildSummaryArgs): string {
  const lines = ['88 Buddhas — Recitation Summary', '─'.repeat(32)];
  if (intention) lines.push(`Intention: ${intention}`);
  if (buddhaStatus) {
    lines.push(`Cycle: ${buddhaStatus.current_cycle || 0}`);
    lines.push(`Total recited: ${buddhaStatus.total_recited || 0}`);
    lines.push(`Mala count: ${buddhaStatus.mala_count || 0}`);
    lines.push(`Dedications: ${buddhaStatus.dedications || 0}`);
    const cb = buddhaStatus.current_buddha;
    if (cb && typeof cb === 'object' && 'name_chinese' in cb && cb.name_chinese) {
      const pinyin = 'name_pinyin' in cb ? (cb as { name_pinyin?: string }).name_pinyin : undefined;
      lines.push(
        `Current: ${cb.name_chinese}` +
        (pinyin ? ` (${pinyin})` : ''),
      );
    }
    if (buddhaStatus.progress_pct != null) {
      lines.push(`Progress: ${Math.round(buddhaStatus.progress_pct)}%`);
    }
  } else {
    lines.push('(No active session — connect via WebSocket to capture live data.)');
  }
  lines.push('─'.repeat(32));
  lines.push('Generated by Vajra.Stream');
  return lines.join('\n');
}

async function copyToClipboard(text: string): Promise<void> {
  // Preferred async Clipboard API (secure contexts only).
  if (navigator.clipboard && window.isSecureContext) {
    await navigator.clipboard.writeText(text);
    return;
  }
  // Legacy fallback: hidden textarea + execCommand.
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.setAttribute('readonly', '');
  ta.style.position = 'absolute';
  ta.style.left = '-9999px';
  document.body.appendChild(ta);
  ta.select();
  try {
    const ok = document.execCommand('copy');
    document.body.removeChild(ta);
    if (!ok) throw new Error('execCommand returned false');
  } catch (err) {
    document.body.removeChild(ta);
    throw err;
  }
}

export default function ShareExport({ buddhaStatus, intention }: ShareExportProps) {
  const addToast = useUIStore((s) => s.addToast);
  const handleCopy = useCallback(async () => {
    const text = buildSummary({ buddhaStatus, intention });
    try {
      await copyToClipboard(text);
      addToast({ type: 'success', title: 'Summary copied to clipboard.', duration: 3 });
    } catch (err) {
      console.error('ShareExport: copy failed', err);
      addToast({ type: 'error', title: 'Could not copy — clipboard unavailable.', duration: 5 });
    }
  }, [buddhaStatus, intention, addToast]);

  const disabled = !buddhaStatus && !intention;

  return (
    <Card
      size="small"
      title={
        <Space size={8} align="center">
          <Share2 size={16} className="text-blue-400" />
          <Title level={5} style={{ margin: 0 }}>Share / Export</Title>
        </Space>
      }
    >
      <Space direction="vertical" size={8} style={{ width: '100%' }}>
        <Text type="secondary" style={{ fontSize: 12 }}>
          Copy a plain-text snapshot of this recitation session to share anywhere.
        </Text>
        <Space size={8} wrap>
          <Button
            type="primary"
            icon={<ClipboardCopy size={14} />}
            onClick={handleCopy}
            disabled={disabled}
          >
            Copy as text
          </Button>
          <Text type="secondary" italic style={{ fontSize: 11 }}>
            <Check size={10} style={{ verticalAlign: 'middle', marginRight: 4 }} />
            No tracking — text stays on your device.
          </Text>
        </Space>
      </Space>
    </Card>
  );
}
