#!/usr/bin/env python3
"""
Seed Chinese Lore — Characters & Locations for Vajra.Stream Outlook

Populates the CharacterManager and LocationManager with Chinese mythological
figures, gods, goddesses, immortals, heroes, and sacred realms from Taoist,
Chinese Buddhist, and folk traditions.

Idempotent — skips any entry whose stable ID already exists.
Usage:   python scripts/seed_chinese_lore.py
"""

import os
import sys

# Ensure project root on path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.core.services.character_manager import (
    CharacterRole,
    CharacterSourceType,
    get_character_manager,
)
from backend.core.services.location_manager import (
    LocationSourceType,
    LocationType,
    get_location_manager,
)

# ──────────────────────────────────────────────
# CHARACTERS  (30 entries)
# ──────────────────────────────────────────────

CHARACTERS = [
    # ── TAOIST DEITIES ──
    {
        "id": "char_jade_emperor",
        "name": "Jade Emperor — Yu Huang Shangdi",
        "role": CharacterRole.DEITY,
        "description": "Supreme ruler of Heaven in Chinese myth and folk religion, overseeing the celestial bureaucracy of 360 ministries. His vast jade palace is the axis of the cosmos.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Majestic, formal pronouncements that ripple like imperial decrees across the firmament",
        "associated_realms": ["loc_celestial_court"],
        "mantra_preference": "taoist_three_purities",
        "elemental_anchor": "aether",
        "priority": 9,
        "tags": ["taoist", "deity", "celestial", "ruler"],
        "notes": "Head of the Chinese celestial pantheon. Year of his birth festival: 9th day of first lunar month.",
    },
    {
        "id": "char_xiwangmu",
        "name": "Queen Mother of the West — Xiwangmu",
        "role": CharacterRole.DEITY,
        "description": "Ancient goddess of immortality dwelling atop Mount Kunlun. Keeper of the Peach Garden whose fruits grant 3,000 years of life. She governs the western paradise, teaches Daoist adepts, and commands an entourage of phoenixes and jade maidens.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Timeless, maternal yet otherworldly — her words taste of peach blossoms and starlight",
        "associated_realms": ["loc_kunlun"],
        "mantra_preference": "taoist_neidan_verse",
        "elemental_anchor": "water",
        "priority": 9,
        "tags": ["taoist", "deity", "immortality", "feminine-divine"],
        "notes": "One of the oldest Chinese deities, dating to oracle-bone inscriptions. Associated with the west, autumn, and metal.",
    },
    {
        "id": "char_laozi",
        "name": "Laozi — Taishang Laojun",
        "role": CharacterRole.MASTER,
        "description": "The deified sage who authored the Dao De Jing and later ascended as the Celestial Venerable of Dao and Virtue (one of the Three Pure Ones). He rides a green ox backward and refines the elixir of immortality in a celestial furnace.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "Paradoxical, sparse, devastatingly precise — speaks in water-worn riddles that only deepen upon reflection",
        "associated_realms": ["loc_kunlun", "loc_wudang", "loc_celestial_court"],
        "mantra_preference": "taoist_tai_shang",
        "elemental_anchor": "water",
        "priority": 10,
        "tags": ["taoist", "sage", "three-purities", "philosopher"],
        "notes": "6th century BCE philosopher; foundation of Daoism. 'The Dao that can be spoken is not the eternal Dao.'",
    },
    {
        "id": "char_doumu",
        "name": "Dou Mu Yuan Jun — Mother of the Big Dipper",
        "role": CharacterRole.DEITY,
        "description": "The stellar goddess who sits at the center of the cosmos holding the Big Dipper — the cosmic clock of fate. She has four heads with three eyes each and eight arms holding celestial implements, yet her expression radiates infinite maternal tenderness.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Utterances that sound like the turning of constellations — measured, luminous, and carrying the weight of cosmic law",
        "associated_realms": ["loc_celestial_court"],
        "mantra_preference": "taoist_dou_mu",
        "elemental_anchor": "aether",
        "priority": 8,
        "tags": ["taoist", "deity", "stars", "feminine-divine", "longevity"],
        "notes": "Adapted from Marici in Buddhism. Governs destiny and the star registers of every living being.",
    },
    {
        "id": "char_zhongli_quan",
        "name": "Zhongli Quan — Chief of the Eight Immortals",
        "role": CharacterRole.MASTER,
        "description": "A Han dynasty general-turned-immortal, first of the Eight Immortals. He carries a feather fan that revives the dead and a peach of immortality. Master of alchemical fire and internal transformation.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "A battle-hardened commander who now speaks in gentle alchemical metaphors — 'The real war is within the crucible'",
        "associated_realms": ["loc_penglai", "loc_celestial_court"],
        "mantra_preference": "taoist_neidan_verse",
        "elemental_anchor": "fire",
        "priority": 7,
        "tags": ["taoist", "eight-immortals", "alchemist", "master"],
        "notes": "Patron of military men turned spiritual. Turns copper to silver with his fan.",
    },
    {
        "id": "char_lu_dongbin",
        "name": "Lü Dongbin — Scholar Immortal of the Sword",
        "role": CharacterRole.ALCHEMIST,
        "description": "The most famous of the Eight Immortals, a Tang dynasty scholar who received the secrets of inner alchemy. He wields a demon-slaying sword of pure yang energy, travels everywhere testing disciples, and dispels worldly illusions with playful ruthlessness.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Quick-witted, piercing, often speaks through dreams — 'You are still dreaming. Wake up.'",
        "associated_realms": ["loc_penglai", "loc_wudang"],
        "mantra_preference": "taoist_golden_light",
        "elemental_anchor": "fire",
        "priority": 8,
        "tags": ["taoist", "eight-immortals", "alchemist", "sword", "yang"],
        "notes": "Patron of scholars and sword-makers. Central figure in Ming/Qing literature.",
    },
    {
        "id": "char_he_xiangu",
        "name": "He Xiangu — Lady Immortal of the Lotus",
        "role": CharacterRole.DEITY,
        "description": "The only female among the Eight Immortals, who ascended after eating the powdered mica of immortality. She carries a lotus flower that radiates healing fragrance, floats above the ground without tiring, and nourishes the sick simply with her presence.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Soft as lotus petals but unshakeable — 'Purity is not refusal; it is knowing what water cannot stain'",
        "associated_realms": ["loc_penglai", "loc_kunlun"],
        "mantra_preference": "chinese_buddhist_guanyin_heart",
        "elemental_anchor": "water",
        "priority": 7,
        "tags": ["taoist", "eight-immortals", "feminine-divine", "healing"],
        "notes": "Tang dynasty. Said to have transformed from a mortal woman who walked from Hunan to the stars.",
    },
    {
        "id": "char_zhang_guolao",
        "name": "Zhang Guolao — Old Immortal of the White Donkey",
        "role": CharacterRole.MASTER,
        "description": "The most eccentric of the Eight Immortals, an ancient sage who rides a paper donkey backward and folds it into his pocket when not riding. He carries a fish-drum and knows the secrets of death, rebirth, and invisibility.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Cackling riddles from the margins — 'Forward is for the young. I prefer watching where I've already been'",
        "associated_realms": ["loc_penglai"],
        "mantra_preference": "taoist_neidan_verse",
        "elemental_anchor": "earth",
        "priority": 7,
        "tags": ["taoist", "eight-immortals", "trickster", "longevity"],
        "notes": "Clouds of breath can turn into mist; associated with necromancy and old age wisdom.",
    },
    {
        "id": "char_nezha",
        "name": "Nezha — Marshal of the Central Altar",
        "role": CharacterRole.GUARDIAN,
        "description": "The child-god of rebellion and protection, born from a three-year pregnancy as a ball of flesh that split open into a radiant boy. He wields a fire-tipped spear, rides wind-fire wheels, and wears the Universe Ring. Fearless protector of children and communities against dragons and demons.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Fierce, defiant, impossibly brave — the voice of a child who refuses to bow to injustice",
        "associated_realms": ["loc_celestial_court", "loc_dragon_palace"],
        "mantra_preference": "taoist_golden_light",
        "elemental_anchor": "fire",
        "priority": 8,
        "tags": ["taoist", "guardian", "hero", "protection", "youth"],
        "notes": "Ming novel 'Fengshen Yanyi'. Revered as a protective deity in folk practice.",
    },
    {
        "id": "char_zhong_kui",
        "name": "Zhong Kui — The Demon Queller",
        "role": CharacterRole.GUARDIAN,
        "description": "A Tang dynasty scholar who, after being unjustly denied honors, became the emperor's dream-guardian against demons. Now he commands 80,000 ghost-soldiers, his fearsome face and iron sword banishing harmful spirits wherever he appears.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Gruff justice, punctuated by ghost-still silence — 'The wronged know the face of wrongness best'",
        "associated_realms": ["loc_celestial_court"],
        "mantra_preference": "taoist_golden_light",
        "elemental_anchor": "earth",
        "priority": 7,
        "tags": ["taoist", "guardian", "exorcist", "justice"],
        "notes": "Traditional paintings of Zhong Kui are hung as protection during Duanwu Festival.",
    },
    {
        "id": "char_guan_yu",
        "name": "Guan Yu — Guan Gong, God of War & Righteousness",
        "role": CharacterRole.HERO,
        "description": "The red-faced general of the Three Kingdoms era, deified as the God of War, Righteousness, and Brotherhood. His guandao (Green Dragon Crescent Blade) weighs 82 jin. Loyal to the point of sainthood, he is venerated across Buddhist, Taoist, and Confucian traditions.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "Stoic honor, laconic thunder — each word a carved oath, never broken, never retracted",
        "associated_realms": ["loc_celestial_court", "loc_wudang"],
        "mantra_preference": "taoist_golden_light",
        "elemental_anchor": "fire",
        "priority": 9,
        "tags": ["taoist", "hero", "warrior", "loyalty", "historical"],
        "notes": "160-220 CE — elevated to saint and deity across Chinese culture. Patron of police, soldiers, and merchants.",
    },
    {
        "id": "char_mazu",
        "name": "Mazu — Empress of Heaven, Guardian of the Sea",
        "role": CharacterRole.DEITY,
        "description": "A Song dynasty Fujian woman who, through compassion and spiritual power, became the Goddess of the Sea. She calms typhoons, guides lost sailors, and appears as a red-clad figure walking across the waves. One of the most beloved folk deities across coastal China and Taiwan.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "Motherly yet oceanic — her speech swells and recedes like tides, carrying lost words home",
        "associated_realms": ["loc_penglai", "loc_dragon_palace"],
        "mantra_preference": "chinese_buddhist_great_compassion",
        "elemental_anchor": "water",
        "priority": 8,
        "tags": ["folk", "deity", "feminine-divine", "sea", "protection"],
        "notes": "Born Lin Mo in 960 CE. Deified posthumously; imperial titles upgraded her to 'Empress of Heaven' (Tianhou).",
    },
    {
        "id": "char_zhu_rong",
        "name": "Zhu Rong — God of Fire",
        "role": CharacterRole.DEITY,
        "description": "The primordial fire deity who tamed the flames of creation and taught humanity to use fire for warmth, cooking, and forging. He rides a pair of fire-dragons and resides at the summit of Mount Kunlun's volcanic heart.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Incandescent and consuming — each sentence crackles like kindling catching flame",
        "associated_realms": ["loc_kunlun", "loc_celestial_court"],
        "mantra_preference": "taoist_golden_light",
        "elemental_anchor": "fire",
        "priority": 7,
        "tags": ["taoist", "deity", "fire", "primordial", "elemental"],
        "notes": "One of the Five Heavenly Emperors of the Warring States cosmology. Guardian of the south.",
    },
    {
        "id": "char_gong_gong",
        "name": "Gong Gong — Water God / Cosmic Antagonist",
        "role": CharacterRole.CUSTOM,
        "description": "The great water god who, in mythic rage, shattered one of the pillars of Heaven (Mount Buzhou), tilting the earth and sky forever. A figure of chaos and transformation — not evil, but an agent of the cataclysm that makes new creation possible.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Boiling anger that cools into sorrowful depth — 'They called me destroyer. I call myself the one who tilted the sky so stars could slide'",
        "associated_realms": [],
        "mantra_preference": None,
        "elemental_anchor": "water",
        "priority": 6,
        "tags": ["taoist", "deity", "water", "chaos", "primordial"],
        "notes": "His battle with Zhuanxu broke Buzhou Mountain, explaining why Chinese rivers flow east and the sky inclines northwest.",
    },
    # ── CREATION GODS & PRIMORDIAL SAGES ──
    {
        "id": "char_pangu",
        "name": "Pangu — The Cosmic Giant",
        "role": CharacterRole.DEITY,
        "description": "The primordial giant who slept inside the cosmic egg for 18,000 years, then separated Heaven and Earth with his awakening. His breath became wind and clouds, his voice thunder, his eyes sun and moon, his body mountains, his blood rivers — the self-sacrifice that birthed the universe.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Almost unheard — geological creaks, the sound of continents shifting — when Pangu speaks at all, it is in creation itself",
        "associated_realms": [],
        "mantra_preference": "taoist_taiji_chant",
        "elemental_anchor": "aether",
        "priority": 9,
        "tags": ["creation", "primordial", "giant", "cosmic"],
        "notes": "Central creation myth recorded in the 'Sanwu Liji' (3rd century CE). The cosmic egg origin story.",
    },
    {
        "id": "char_nuwa",
        "name": "Nüwa — Mother Goddess, Mender of Heaven",
        "role": CharacterRole.DEITY,
        "description": "The serpent-bodied creatrix who shaped humanity from yellow river clay. When the sky shattered and floods engulfed the world, she smelted five-colored stones to repair the cracked heavens, cut a cosmic turtle's legs to prop up the four corners, and restored order. Goddess of creation, marriage, and cosmic repair.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Tender as a mother shaping her first child from mud, vast as the sky she once repaired — 'I did not make you perfect. I made you capable of mending'",
        "associated_realms": ["loc_kunlun"],
        "mantra_preference": "taoist_taiji_chant",
        "elemental_anchor": "earth",
        "priority": 10,
        "tags": ["creation", "feminine-divine", "primordial", "repair"],
        "notes": "One of the oldest Chinese deities. Her union with Fuxi is the foundation myth of civilization.",
    },
    {
        "id": "char_fuxi",
        "name": "Fuxi — First Sovereign, Inventor of the Bagua",
        "role": CharacterRole.MASTER,
        "description": "The serpent-bodied first cultural hero who taught humanity fishing, hunting, cooking, and writing. He discovered the Eight Trigrams (Bagua) by observing the marks on a dragon-horse emerging from the Yellow River — the foundation of the I Ching. Husband and brother of Nüwa, co-creator of civilization.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Scrolls unfurling — each phrase maps a pattern, each silence contains a hexagram — 'Look at the river. The answer is already arranged'",
        "associated_realms": [],
        "mantra_preference": "taoist_eight_trigrams",
        "elemental_anchor": "air",
        "priority": 9,
        "tags": ["creation", "sage", "divination", "bagua", "primordial"],
        "notes": "The earliest culture hero in Chinese mythology. Paired with Nüwa as the original human couple.",
    },
    {
        "id": "char_shennong",
        "name": "Shennong — Divine Farmer, Emperor of the Five Grains",
        "role": CharacterRole.HERO,
        "description": "The ox-headed god-hero who tasted hundreds of herbs to discover their medicinal properties — sometimes poisoning himself daily and resurrecting. He invented the plow, agriculture, tea, acupuncture, and the farmer's calendar. Embodiment of self-sacrificing experimentation for the good of all.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Warm, earthy pragmatism — 'Let me try it first. If I survive, you eat it. If not — write it down'",
        "associated_realms": [],
        "mantra_preference": None,
        "elemental_anchor": "earth",
        "priority": 8,
        "tags": ["hero", "sage", "medicine", "agriculture", "primordial"],
        "notes": "One of the Three Sovereigns. The 'Shennong Bencao Jing' (Classic of Herbal Medicine) is attributed to him.",
    },
    {
        "id": "char_yellow_emperor",
        "name": "Yellow Emperor — Huangdi, Father of Chinese Civilization",
        "role": CharacterRole.MASTER,
        "description": "The legendary sage-king who unified the tribes, invented writing, medicine (the Huangdi Neijing), the compass, silk weaving, and the calendar. In his great battle against Chi You, he called down celestial armies and a drought demon to secure victory. He ascended to immortality on a golden dragon.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "Imperial forethought — every word is both command and teaching, a seed planted for ten thousand generations",
        "associated_realms": ["loc_celestial_court", "loc_kunlun"],
        "mantra_preference": "taoist_tai_shang",
        "elemental_anchor": "earth",
        "priority": 9,
        "tags": ["sage", "historical", "civilization", "medicine", "ruler"],
        "notes": "Ancestor of all Han Chinese. The 'Huangdi Neijing' remains foundational to TCM.",
    },
    {
        "id": "char_hou_yi",
        "name": "Hou Yi — The Divine Archer",
        "role": CharacterRole.HERO,
        "description": "The greatest archer in myth, who shot down nine of the ten sun-birds that scorched the earth, leaving only one. He won the elixir of immortality from Xiwangmu but lost it to his wife Chang'e, who ascended to the moon alone. A figure of tragic heroism — the mortal who saved the world but could not save himself from mortality.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "A bowstring's tension — few words, drawn taut, released with precise, wounding honesty",
        "associated_realms": ["loc_kunlun"],
        "mantra_preference": None,
        "elemental_anchor": "fire",
        "priority": 8,
        "tags": ["hero", "archer", "solar", "tragic", "mythology"],
        "notes": "Central figure of Mid-Autumn Festival myth. The ten suns were the children of Di Jun.",
    },
    {
        "id": "char_change",
        "name": "Chang'e — Goddess of the Moon",
        "role": CharacterRole.DEITY,
        "description": "The luminous goddess who dwells alone in the Moon Palace, having drunk the elixir of immortality that was meant for her husband Hou Yi. Accompanied by a jade rabbit pounding the elixir, she embodies solitude, lunar beauty, eternal longing, and the quiet radiance that only comes from losing what one loved most.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Whispered through silver light — 'The moon is full of absence. That is precisely why it glows'",
        "associated_realms": ["loc_moon_palace"],
        "mantra_preference": "taoist_tai_shang",
        "elemental_anchor": "water",
        "priority": 8,
        "tags": ["deity", "feminine-divine", "moon", "immortality", "tragic"],
        "notes": "Honored at the Mid-Autumn Festival with mooncakes and lanterns.",
    },
    # ── CHINESE BUDDHIST FIGURES ──
    {
        "id": "char_guanyin_chinese",
        "name": "Guanyin — Goddess of Mercy (Chinese Aspect)",
        "role": CharacterRole.DEITY,
        "description": "The thousand-armed, thousand-eyed Bodhisattva of Compassion who hears the cries of all suffering beings. In her Chinese form she often appears as a white-robed woman holding a willow branch and vase of pure water, pouring compassion upon the world. 'She who hears the cries of the world' — the most beloved deity in Chinese Buddhism.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Oceanic compassion in human form — 'Put down the weight. I have already carried it for you'",
        "associated_realms": ["loc_putuo_shan", "loc_sukhavati"],
        "mantra_preference": "chinese_buddhist_great_compassion",
        "elemental_anchor": "water",
        "priority": 10,
        "tags": ["buddhist", "deity", "compassion", "feminine-divine", "guanyin"],
        "notes": "Indian Avalokiteshvara transformed into feminine form in China over centuries. 'One who perceives sounds.'",
    },
    {
        "id": "char_xuanzang",
        "name": "Xuanzang — The Tang Monk",
        "role": CharacterRole.STUDENT,
        "description": "The historic Tang dynasty monk who undertook a 17-year pilgrimage to India across deserts and mountains to bring authentic Buddhist scriptures back to China. Returning with 657 sutras, he spent the rest of his life translating them. The epitome of unwavering determination on the spiritual path.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "Scholar-monk precision — 'Each step to India was a verse of the sutra I had not yet received'",
        "associated_realms": ["loc_emei", "loc_bodh_gaya"],
        "mantra_preference": "chinese_buddhist_amituofo_nianfo",
        "elemental_anchor": "earth",
        "priority": 8,
        "tags": ["buddhist", "pilgrim", "scholar", "historical", "journey"],
        "notes": "602-664 CE. Became the model for Tang Seng in Journey to the West. Founded Faxiang (Consciousness-Only) school.",
    },
    {
        "id": "char_sun_wukong",
        "name": "Sun Wukong — The Monkey King, Great Sage Equal to Heaven",
        "role": CharacterRole.HERO,
        "description": "Born from a stone egg fertilized by wind, this immortal monkey mastered 72 transformations, somersaulted across 108,000 li, challenged Heaven itself, and was imprisoned under a mountain for 500 years before becoming the Tang Monk's protector on the journey west. He wields the Ruyi Jingu Bang, a golden staff that once anchored the ocean floor, and sees through all illusions with his fire-golden eyes.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Irreverent genius — equal parts Buddhist insight and monkey mischief — 'Old Sun has a question that's also a stick to the face'",
        "associated_realms": ["loc_celestial_court", "loc_emei", "loc_dragon_palace"],
        "mantra_preference": "chinese_buddhist_guanyin_heart",
        "elemental_anchor": "air",
        "priority": 10,
        "tags": ["buddhist", "hero", "trickster", "monkey", "journey-to-the-west"],
        "notes": "Central figure of 'Journey to the West'. Represents the untamed mind tamed by wisdom. Most beloved character in Chinese literature.",
    },
    {
        "id": "char_ji_gong",
        "name": "Ji Gong — The Crazy Monk",
        "role": CharacterRole.CUSTOM,
        "description": "The Chan Buddhist folk hero who violated every monastic rule while radiating pure enlightenment. A wandering, wine-drinking, meat-eating monk with tattered robes and a worn-out fan, who healed the sick, exposed hypocrisy, and helped the poor — all while cackling at the absurdity of rigid spiritual pride.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "Drunken truth-telling — 'Monastic rules are just training wheels. I learned to ride the dragon instead'",
        "associated_realms": [],
        "mantra_preference": "chinese_buddhist_amituofo_nianfo",
        "elemental_anchor": "air",
        "priority": 8,
        "tags": ["buddhist", "trickster", "folk-hero", "compassion"],
        "notes": "Historical monk Daoji (1130-1207). Became a folk hero-healer in Southern Song folklore.",
    },
    {
        "id": "char_dizang",
        "name": "Dizang Wang — Ksitigarbha, Savior of Hell",
        "role": CharacterRole.DEITY,
        "description": "The bodhisattva who vowed: 'Until the hells are empty, I will not become a Buddha.' He descends into the darkest realms carrying a staff that rings open hell-gates and a wish-fulfilling jewel that illuminates the suffering of the deceased. Guardian of children, travelers, and the unborn.",
        "source_type": CharacterSourceType.MYTHOLOGY,
        "dialogue_style": "Bottomless patience — 'I have time. I have all the time there is. Every being in hell will eventually look up'",
        "associated_realms": ["loc_jiuhua_shan"],
        "mantra_preference": "chinese_buddhist_ksitigarbha",
        "elemental_anchor": "earth",
        "priority": 9,
        "tags": ["buddhist", "deity", "underworld", "ancestors", "compassion"],
        "notes": "Principal deity of Jiuhua Shan. His festival is the 30th day of the 7th lunar month (Ghost Festival).",
    },
    # ── LEGENDARY HEROES ──
    {
        "id": "char_yu_the_great",
        "name": "Yu the Great — Tamer of the Flood",
        "role": CharacterRole.HERO,
        "description": "The sage-king who spent 13 years taming the primordial floodwaters that had drowned all of China — not by building dams like his failed father Gun, but by dredging rivers and carving channels into the sea. He passed his own home three times without entering. His mastery of water flow became the model of wu-wei in action.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "A man who learned the language of rivers — 'Water wins by yielding. So I too will yield until it follows me to the sea'",
        "associated_realms": [],
        "mantra_preference": None,
        "elemental_anchor": "water",
        "priority": 8,
        "tags": ["hero", "flood", "sage-king", "wu-wei", "perseverance"],
        "notes": "Founder of the Xia dynasty. His flood-control works are the foundation myth of Chinese hydraulic civilization.",
    },
    {
        "id": "char_huamulan",
        "name": "Hua Mulan — The Warrior Maiden",
        "role": CharacterRole.HERO,
        "description": "The young woman who disguised herself as a man to take her aging father's place in the imperial army, serving with distinction for twelve years before returning home to her loom. Her comrades discovered her gender only when she welcomed them in woman's dress. Emblem of filial piety, courage, and the transcendence of gender roles.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "Sword-calm directness — 'The enemy does not care whether I am a woman. Neither do I'",
        "associated_realms": [],
        "mantra_preference": None,
        "elemental_anchor": "earth",
        "priority": 8,
        "tags": ["hero", "warrior", "feminine", "filial-piety", "historical"],
        "notes": "Northern Wei dynasty (386-535 CE). The 'Ballad of Mulan' is the earliest surviving account.",
    },
    {
        "id": "char_yue_fei",
        "name": "Yue Fei — The Loyal General",
        "role": CharacterRole.HERO,
        "description": "The Song dynasty general whose back was tattooed with 'Serve the Country with Utmost Loyalty' (盡忠報國) by his mother. An undefeated military genius who reclaimed vast territory from Jurchen invaders, he was betrayed and executed on false charges — then posthumously deified as a symbol of absolute honor.",
        "source_type": CharacterSourceType.HISTORICAL,
        "dialogue_style": "Unbreakable conviction — 'They can take my life. They cannot take the four characters my mother wrote on my back'",
        "associated_realms": [],
        "mantra_preference": None,
        "elemental_anchor": "earth",
        "priority": 8,
        "tags": ["hero", "warrior", "loyalty", "martyr", "historical"],
        "notes": "1103-1142. Worshiped at Yue Fei Temple in Hangzhou, where the traitor Qin Hui is kneeled in iron before his statue.",
    },
]

# ═══════════════════════════════════════════════
# LOCATIONS / REALMS  (10 entries)
# ═══════════════════════════════════════════════

LOCATIONS = [
    {
        "id": "loc_kunlun",
        "name": "Mount Kunlun — Paradise of the Immortals",
        "description": "The cosmic mountain at the western edge of the world, axis mundi of Chinese mythology. Xiwangmu's palace perches at its summit amidst the Peach Garden of Immortality. Nine-story jade terraces ascend into the void, jewel-trees bear fruit of eternal life, and the Ruoshui (Weak Water) river encircles it — no ordinary soul can cross.",
        "location_type": LocationType.METAPHYSICAL_REALM,
        "source_type": LocationSourceType.MYTHOLOGY,
        "is_metaphysical": True,
        "latitude": 35.9,
        "longitude": 80.0,
        "timezone": "Asia/Urumqi",
        "celestial_coordinates": "Western Quadrant / Axis Mundi / Weak Water Meridian",
        "dimension_frequency": 528.0,
        "realm_governor": "Xiwangmu (Queen Mother of the West)",
        "astrological_anchor": "Venus in Taurus, Saturn at the Western Gate",
        "elemental_affinity": "Jade / Immortal Fire / Water",
        "priority": 9,
        "tags": ["taoist", "immortality", "axis-mundi", "paradise", "mountain"],
        "notes": "Real-world Kunlun mountain range also exists in western China, but the mythological Kunlun is a metaphysical realm that encompasses and transcends the physical range.",
    },
    {
        "id": "loc_penglai",
        "name": "Penglai — Island of the Blessed Immortals",
        "description": "The fabled isle in the Eastern Sea where the Eight Immortals reside. Everything here is white — white birds, white palaces, white jade and pearl. No frost or snow ever touches it. The mountains of Penglai are held aloft by giant tortoises, and the wine of immortality flows freely. Mortals who sail toward it see it hovering as a mirage on the horizon, forever unreachable without spiritual merit.",
        "location_type": LocationType.METAPHYSICAL_REALM,
        "source_type": LocationSourceType.MYTHOLOGY,
        "is_metaphysical": True,
        "latitude": 37.8,
        "longitude": 122.0,
        "timezone": "Asia/Shanghai",
        "celestial_coordinates": "Eastern Oceanic Quadrant / Tortoise-Borne Archipelago",
        "dimension_frequency": 396.0,
        "realm_governor": "The Eight Immortals (collective council)",
        "astrological_anchor": "Neptune in Pisces, Moon in Cancer",
        "elemental_affinity": "Mist / Pearl / Salt",
        "priority": 8,
        "tags": ["taoist", "immortality", "island", "paradise", "eight-immortals"],
        "notes": "One of five fabled islands. Qin Shi Huang sent expeditions to find it. The mirage phenomenon off Penglai (Shandong) coastal waters is still observed today.",
    },
    {
        "id": "loc_celestial_court",
        "name": "Heavenly Court — Tianting, Jade Emperor's Palace",
        "description": "The celestial bureaucracy at the center of the heavens, modeled on imperial China but wrought in jade, gold, and starlight. 36 heavens and 72 earthly abodes orbit this center, connected by the Southern Gate (Nan Tian Men). The Jade Emperor presides from the Hall of Numinous Empyrean, flanked by four heavenly kings, thousands of star officials, and the registers of every living being's fate.",
        "location_type": LocationType.COSMIC_ANCHOR,
        "source_type": LocationSourceType.MYTHOLOGY,
        "is_metaphysical": True,
        "latitude": None,
        "longitude": None,
        "timezone": "Celestial Standard",
        "celestial_coordinates": "Central Galactic Core / Pole Star Anchor / Nan Tian Men Gate",
        "dimension_frequency": 963.0,
        "realm_governor": "Jade Emperor (Yuhuang Shangdi)",
        "astrological_anchor": "Sun conjunct Polaris, Jupiter in Leo",
        "elemental_affinity": "Aether / Gold / Starlight",
        "priority": 9,
        "tags": ["taoist", "celestial", "palace", "bureaucracy", "heaven"],
        "notes": "The celestial hierarchy mirrors the earthly imperial system. Accessed through the Southern Gate, guarded by the Four Heavenly Kings.",
    },
    {
        "id": "loc_moon_palace",
        "name": "Guanghan Palace — Palace of Vast Cold, The Moon",
        "description": "Chang'e's solitary crystalline palace on the moon, surrounded by osmanthus trees whose fragrance drifts across the void. The Jade Rabbit eternally pounds immortality elixir in a mortar. The woodsman Wu Gang endlessly chops a self-healing osmanthus tree — his punishment for seeking immortality without merit. A place of exquisite, melancholic stillness.",
        "location_type": LocationType.METAPHYSICAL_REALM,
        "source_type": LocationSourceType.MYTHOLOGY,
        "is_metaphysical": True,
        "latitude": None,
        "longitude": None,
        "timezone": "Lunar Standard",
        "celestial_coordinates": "Lunar Body / Osmanthus Meridian / Jade Rabbit Sector",
        "dimension_frequency": 432.0,
        "realm_governor": "Chang'e (Goddess of the Moon)",
        "astrological_anchor": "Moon at 15° Cancer / Full Moon conjunction",
        "elemental_affinity": "Silver / Frost / Osmanthus",
        "priority": 8,
        "tags": ["mythology", "moon", "immortality", "solitude", "feminine-divine"],
        "notes": "Celebrated during Mid-Autumn Festival. The 'Guang Han Gong' appears in countless poems and paintings.",
    },
    {
        "id": "loc_dragon_palace",
        "name": "Dragon King's Crystal Palace — Long Wang Jing Gong",
        "description": "Beneath the eastern ocean, the Dragon King Ao Guang holds court in a palace of coral, pearl, and translucent crystal. Its halls are lit by phosphorescent deep-sea jewels. The four Dragon Kings of the Four Seas rule from similar palaces, commanding armies of shrimp soldiers and crab generals, controlling rainfall and tides across the realm.",
        "location_type": LocationType.METAPHYSICAL_REALM,
        "source_type": LocationSourceType.MYTHOLOGY,
        "is_metaphysical": True,
        "latitude": 25.0,
        "longitude": 130.0,
        "timezone": "Pacific/Midway",
        "celestial_coordinates": "Eastern Sea Abyss / Dragon Meridian Trench",
        "dimension_frequency": 285.0,
        "realm_governor": "Ao Guang, Dragon King of the Eastern Sea",
        "astrological_anchor": "Neptune conjunct Ascendant, Draco constellation",
        "elemental_affinity": "Water / Crystal / Abyssal",
        "priority": 8,
        "tags": ["folk", "dragon", "ocean", "palace", "water"],
        "notes": "Source of Sun Wukong's Ruyi Jingu Bang — the pillar that once held the ocean floor. The Dragon Kings control regional weather.",
    },
    {
        "id": "loc_wudang",
        "name": "Mount Wudang — Taoist Sacred Mountain",
        "description": "The earthly seat of Taoist martial and inner cultivation, where the immortal Zhenwu (Perfected Warrior / Xuan Wu) achieved the Dao. A complex of 72 peaks and 36 cliff monasteries draped in mist, where the sound of swords practicing taiji cuts through cloud banks. The birthplace of Wudang internal martial arts and beacon of Taoist alchemical practice.",
        "location_type": LocationType.EARTHLY_SACRED,
        "source_type": LocationSourceType.GEOGRAPHIC,
        "is_metaphysical": False,
        "latitude": 32.4,
        "longitude": 111.0,
        "timezone": "Asia/Shanghai",
        "celestial_coordinates": None,
        "dimension_frequency": 528.0,
        "realm_governor": "Zhenwu Dadi (Perfected Warrior / Xuan Wu)",
        "astrological_anchor": "Saturn in Capricorn, Black Tortoise constellation",
        "elemental_affinity": "Metal / Mist / Mountain",
        "priority": 7,
        "tags": ["taoist", "sacred-mountain", "martial-arts", "taiji", "geographic"],
        "notes": "UNESCO World Heritage site. The Golden Hall is one of the largest gilded copper temples in China.",
    },
    {
        "id": "loc_emei",
        "name": "Mount Emei — Sacred Mountain of Samantabhadra",
        "description": "One of the four sacred Buddhist mountains of China, rising from the Sichuan basin into a sea of clouds. The bodhisattva Samantabhadra (Puxian) presides here on a white elephant with six tusks. Golden summit temples catch the first light of dawn above the cloud line, and the 'Buddha's Light' — a glorious rainbow halo — manifests on misty afternoons.",
        "location_type": LocationType.EARTHLY_SACRED,
        "source_type": LocationSourceType.GEOGRAPHIC,
        "is_metaphysical": False,
        "latitude": 29.5,
        "longitude": 103.3,
        "timezone": "Asia/Shanghai",
        "celestial_coordinates": None,
        "dimension_frequency": 639.0,
        "realm_governor": "Puxian Pusa (Samantabhadra Bodhisattva)",
        "astrological_anchor": "Jupiter in Sagittarius, Sun in Leo",
        "elemental_affinity": "Cloud / Light / Gold",
        "priority": 8,
        "tags": ["buddhist", "sacred-mountain", "meditation", "geographic"],
        "notes": "UNESCO World Heritage. The Jinding (Golden Summit) is at 3,079m. First Buddhist temple built in the 1st century CE.",
    },
    {
        "id": "loc_putuo_shan",
        "name": "Mount Putuo — Guanyin's Island Sanctuary",
        "description": "A small island off the Zhejiang coast, sacred to Guanyin (Avalokiteshvara). The bodhisattva's presence is said to permeate every slope, every sea cave, every temple bell. Pilgrims circumambulate the island hearing only waves and devotion. Lotus-shaped rocks emerge from the surf at low tide. The sound of 'Namo Guanshiyin Pusa' rides the salt wind day and night.",
        "location_type": LocationType.EARTHLY_SACRED,
        "source_type": LocationSourceType.GEOGRAPHIC,
        "is_metaphysical": False,
        "latitude": 30.0,
        "longitude": 122.4,
        "timezone": "Asia/Shanghai",
        "celestial_coordinates": None,
        "dimension_frequency": 528.0,
        "realm_governor": "Guanyin (Avalokiteshvara Bodhisattva)",
        "astrological_anchor": "Moon in Pisces, Venus in Cancer",
        "elemental_affinity": "Sea / Lotus / Compassion",
        "priority": 9,
        "tags": ["buddhist", "sacred-island", "compassion", "guanyin", "geographic"],
        "notes": "One of the four sacred Buddhist mountains. The 33m Guanyin statue faces the sea. The bodhisattva is said to have appeared here in 863 CE.",
    },
    {
        "id": "loc_jiuhua_shan",
        "name": "Mount Jiuhua — Realm of Ksitigarbha",
        "description": "The sacred Buddhist mountain of Anhui where Ksitigarbha Bodhisattva (Dizang Wang) is venerated. Ninety-nine peaks pierce the mist, their shapes like lotus petals unfolding. Temples cling to precipices and incense drifts through bamboo groves. This is the bridge between the living and the dead — prayers spoken here are said to reach ancestors in the deepest hell realms.",
        "location_type": LocationType.EARTHLY_SACRED,
        "source_type": LocationSourceType.GEOGRAPHIC,
        "is_metaphysical": False,
        "latitude": 30.5,
        "longitude": 117.8,
        "timezone": "Asia/Shanghai",
        "celestial_coordinates": None,
        "dimension_frequency": 396.0,
        "realm_governor": "Dizang Wang Pusa (Ksitigarbha Bodhisattva)",
        "astrological_anchor": "Pluto in Scorpio, Saturn's South Node",
        "elemental_affinity": "Stone / Incense / Root",
        "priority": 8,
        "tags": ["buddhist", "sacred-mountain", "ancestors", "underworld", "geographic"],
        "notes": "One of the four sacred Buddhist mountains. The bodhisattva Kim Kiaokak (a Silla prince) was recognized as Ksitigarbha's manifestation.",
    },
    {
        "id": "loc_mount_tai",
        "name": "Mount Tai — Eastern Sacred Peak, Gate of the Sun",
        "description": "The most revered of the Five Great Mountains, standing in Shandong as the eastern pillar where the sun first touches Chinese soil. For 3,000 years, emperors have climbed its 6,600 stone steps to perform the Fengshan sacrifice — reporting to Heaven (feng) and Earth (shan) that the realm is in order. The Jade Emperor's summit temple marks the closest point between earth and heaven.",
        "location_type": LocationType.EARTHLY_SACRED,
        "source_type": LocationSourceType.GEOGRAPHIC,
        "is_metaphysical": False,
        "latitude": 36.3,
        "longitude": 117.1,
        "timezone": "Asia/Shanghai",
        "celestial_coordinates": None,
        "dimension_frequency": 528.0,
        "realm_governor": "Dongyue Dadi (Great Emperor of the Eastern Peak)",
        "astrological_anchor": "Sun at the Ascendant, Jupiter in Aries",
        "elemental_affinity": "Granite / Dawn / Eastern Wood",
        "priority": 9,
        "tags": ["taoist", "sacred-mountain", "imperial", "sun", "geographic"],
        "notes": "UNESCO World Heritage. The Fengshan ceremony was last performed by Emperor Qianlong. Associated with birth and renewal.",
    },
]


# ──────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────


def seed():
    char_mgr = get_character_manager()
    loc_mgr = get_location_manager()

    chars_added = 0
    chars_skipped = 0
    locs_added = 0
    locs_skipped = 0

    print("=" * 60)
    print("🌏  Seeding Chinese Lore into Vajra.Stream Outlook")
    print("=" * 60)

    for data in CHARACTERS:
        cid = data.pop("id")
        if char_mgr.get_character(cid):
            print(f"  ⏭️  SKIP character: {data['name']} (already exists)")
            chars_skipped += 1
            continue
        char_mgr.create_character(character_id=cid, **data)
        print(f"  ✅ ADDED character: {data['name']} ({data['role'].value})")
        chars_added += 1

    print()

    for data in LOCATIONS:
        lid = data.pop("id")
        if loc_mgr.get_location(lid):
            print(f"  ⏭️  SKIP location:  {data['name']} (already exists)")
            locs_skipped += 1
            continue
        loc_mgr.create_location(location_id=lid, **data)
        print(f"  ✅ ADDED location:  {data['name']} ({data['location_type'].value})")
        locs_added += 1

    print()
    print("=" * 60)
    print("📊  SUMMARY")
    print(f"  Characters:  {chars_added} added, {chars_skipped} skipped")
    print(f"  Locations:   {locs_added} added, {locs_skipped} skipped")
    print(f"  Total seeded: {chars_added + locs_added}")
    print("=" * 60)

    # Print a sample view of what's now in the stores
    all_chars = char_mgr.get_all_characters()
    all_locs = loc_mgr.get_all_locations()
    print(f"\n  Total characters now in system: {len(all_chars)}")
    print(f"  Total locations now in system:  {len(all_locs)}")


if __name__ == "__main__":
    seed()
