export interface DeityVisualization {
  id: string;
  name: string;
  sanskritName: string;
  bija: string;
  bijaRomaji: string;
  bodyColor: string;
  bodyColorName: string;
  radianceColor: string;
  lotusColor: string;
  hasMoonDisk: boolean;
  hasSunDisk: boolean;
  sunDiskPosition: 'below' | 'above' | 'none';
  mudra: string;
  rightHandAttribute: string;
  leftHandAttribute: string;
  pureLand: string;
  element: string;
  chakra: string;
  frequencyHz: number;
  emissionColor: string;
  vowEssence: string;
}

export const DEITY_VISUALIZATIONS: Record<string, DeityVisualization> = {
  green_tara: {
    id: 'green_tara',
    name: 'Green Tārā',
    sanskritName: 'Śyāmatārā',
    bija: 'तां',
    bijaRomaji: 'TĀṂ',
    bodyColor: '#22c55e',
    bodyColorName: 'Emerald Green',
    radianceColor: '#4ade80',
    lotusColor: '#06b6d4',
    hasMoonDisk: true,
    hasSunDisk: false,
    sunDiskPosition: 'none',
    mudra: 'Varada + Abhaya (boon-giving + fearlessness)',
    rightHandAttribute: 'Varada mudrā at right knee (boon-giving)',
    leftHandAttribute: 'Blue utpala lotus at heart (night-blooming celestial lotus)',
    pureLand: 'Potalaka Mountain (Southern Wish-Fulfilling Mountain)',
    element: 'Air (Wind)',
    chakra: 'heart',
    frequencyHz: 528,
    emissionColor: '#4ade80',
    vowEssence: 'Swift liberation from the eight great fears and all obstacles',
  },

  white_tara: {
    id: 'white_tara',
    name: 'White Tārā',
    sanskritName: 'Sitatārā',
    bija: 'तां',
    bijaRomaji: 'TĀṂ',
    bodyColor: '#f8fafc',
    bodyColorName: 'Pure White (Moon Crystal)',
    radianceColor: '#e0f2fe',
    lotusColor: '#f1f5f9',
    hasMoonDisk: true,
    hasSunDisk: false,
    sunDiskPosition: 'none',
    mudra: 'Varada at heart (both hands)',
    rightHandAttribute: 'Varada mudrā at heart (bestowing boons of long life)',
    leftHandAttribute: 'White lotus stem + seven eyes of omniscient vision',
    pureLand: 'The Luminous Moon Realm',
    element: 'Space',
    chakra: 'crown',
    frequencyHz: 396,
    emissionColor: '#e0f2fe',
    vowEssence: 'Healing, longevity, restoration of vitality',
  },

  medicine_buddha: {
    id: 'medicine_buddha',
    name: 'Medicine Buddha',
    sanskritName: 'Bhaiṣajyaguru',
    bija: 'भै',
    bijaRomaji: 'BHAI',
    bodyColor: '#1e40af',
    bodyColorName: 'Lapis Lazuli Blue',
    radianceColor: '#3b82f6',
    lotusColor: '#2563eb',
    hasMoonDisk: true,
    hasSunDisk: false,
    sunDiskPosition: 'none',
    mudra: 'Varada (supreme giving) over right knee',
    rightHandAttribute: 'Myrobalan plant (arura) — king of medicinal herbs',
    leftHandAttribute: 'Lapis lazuli begging bowl filled with healing nectar (amṛta)',
    pureLand: 'Eastern Pure Land of Pure Lapis Lazuli (Vaiḍūryanirbhāsa)',
    element: 'Water',
    chakra: 'third_eye',
    frequencyHz: 285,
    emissionColor: '#60a5fa',
    vowEssence: 'The 12 great vows to heal all illness of body, speech, and mind',
  },

  vajrasattva: {
    id: 'vajrasattva',
    name: 'Vajrasattva',
    sanskritName: 'Vajrasattva',
    bija: 'हूँ',
    bijaRomaji: 'HŪṂ',
    bodyColor: '#f8fafc',
    bodyColorName: 'Pure White (Crystal/Snow)',
    radianceColor: '#e2e8f0',
    lotusColor: '#cbd5e1',
    hasMoonDisk: true,
    hasSunDisk: false,
    sunDiskPosition: 'none',
    mudra: 'Vajra-hum-kara (vajra at heart, bell at hip)',
    rightHandAttribute: 'Five-pronged vajra (diamond scepter) at heart — method/compassion',
    leftHandAttribute: 'Bell (ghaṇṭā) at hip — wisdom/emptiness',
    pureLand: 'Primordial Pure Land of the Dharmadhātu (Akanistha Realm)',
    element: 'Space',
    chakra: 'crown',
    frequencyHz: 396,
    emissionColor: '#f1f5f9',
    vowEssence: 'Purification of all negative karma and obscurations; primordial purity of mind',
  },

  amitabha: {
    id: 'amitabha',
    name: 'Amitābha',
    sanskritName: 'Amitābha (Infinite Light)',
    bija: 'ह्रीः',
    bijaRomaji: 'HRĪḤ',
    bodyColor: '#dc143c',
    bodyColorName: 'Amitabha Red (Sunset Crimson)',
    radianceColor: '#ef4444',
    lotusColor: '#f87171',
    hasMoonDisk: true,
    hasSunDisk: true,
    sunDiskPosition: 'below',
    mudra: 'Dhyāna (meditation mudrā) in lap',
    rightHandAttribute: 'Both hands in dhyāna mudrā resting in lap',
    leftHandAttribute: 'Begging bowl (patra) filled with nectar of immortality',
    pureLand: 'Sukhāvatī — Western Realm of Great Bliss',
    element: 'Fire',
    chakra: 'throat',
    frequencyHz: 174,
    emissionColor: '#fca5a5',
    vowEssence: 'The 48 vows — rebirth in Pure Land through faith and recitation',
  },

  avalokiteshvara: {
    id: 'avalokiteshvara',
    name: 'Avalokiteśvara',
    sanskritName: 'Avalokiteśvara (Chenrezig)',
    bija: 'ह्रीः',
    bijaRomaji: 'HRĪḤ',
    bodyColor: '#fafafa',
    bodyColorName: 'Brilliant White (suffused with green and pink)',
    radianceColor: '#86efac',
    lotusColor: '#ffffff',
    hasMoonDisk: true,
    hasSunDisk: false,
    sunDiskPosition: 'none',
    mudra: 'Añjali (hands together at heart) holding wish-fulfilling gem',
    rightHandAttribute: 'Crystal vase of healing nectar + wish-fulfilling gem (cintāmaṇi)',
    leftHandAttribute: 'White lotus of purity + mala for recitation',
    pureLand: 'Potalaka Mountain (also regent of Sukhāvatī)',
    element: 'Wind',
    chakra: 'heart',
    frequencyHz: 639,
    emissionColor: '#bbf7d0',
    vowEssence: 'Compassion for all who suffer — hearing every cry for help',
  },

  heart_sutra: {
    id: 'heart_sutra',
    name: 'Prajñāpāramitā',
    sanskritName: 'Prajñāpāramitā Devī (Heart Sūtra Mother)',
    bija: 'प्र',
    bijaRomaji: 'PRA',
    bodyColor: '#fbbf24',
    bodyColorName: 'Golden Yellow (Refined Gold)',
    radianceColor: '#fcd34d',
    lotusColor: '#fde68a',
    hasMoonDisk: true,
    hasSunDisk: true,
    sunDiskPosition: 'below',
    mudra: 'Dharma-teaching mudrā (dharmacakra)',
    rightHandAttribute: 'Vajra or golden Prajñāpāramitā text on blue lotus',
    leftHandAttribute: 'Blue utpala lotus supporting the Perfection of Wisdom text',
    pureLand: 'The Dharmadhātu Expanse — ultimate pure land of wisdom',
    element: 'Space',
    chakra: 'third_eye',
    frequencyHz: 852,
    emissionColor: '#fef3c7',
    vowEssence: 'Realization of emptiness — the mother who gives birth to all Buddhas',
  },

  zhunti: {
    id: 'zhunti',
    name: 'Cuṇḍī Buddha Mother',
    sanskritName: 'Cuṇḍī (准提佛母)',
    bija: '准',
    bijaRomaji: 'CUNDĪ',
    bodyColor: '#fef3c7',
    bodyColorName: 'White-Gold (Ivory with Golden Radiance)',
    radianceColor: '#fde68a',
    lotusColor: '#fef9c3',
    hasMoonDisk: true,
    hasSunDisk: false,
    sunDiskPosition: 'none',
    mudra: 'Cuṇḍī Mudrā — fingers interlocked, both index fingers pointing upward',
    rightHandAttribute: '18 arms each holding Dharma implements (vajra, wheel, lotus, sword, etc.)',
    leftHandAttribute: 'Part of the 18-arm emanation representing the 18 āveṇika-dharmāḥ',
    pureLand: 'The Lotus Treasury Realm',
    element: 'Fire',
    chakra: 'solar_plexus',
    frequencyHz: 417,
    emissionColor: '#fef08a',
    vowEssence: 'Purification of all obscurations + wish-fulfillment — accessible to all without empowerment',
  },

  '88_buddhas': {
    id: '88_buddhas',
    name: '88 Buddhas',
    sanskritName: 'Aṣṭāśīti Buddha Sādhana',
    bija: 'अ',
    bijaRomaji: 'A (Akṣara — Primordial Sound)',
    bodyColor: '#fbbf24',
    bodyColorName: 'Golden (Buddha-field Gold)',
    radianceColor: '#fcd34d',
    lotusColor: '#fef3c7',
    hasMoonDisk: true,
    hasSunDisk: true,
    sunDiskPosition: 'above',
    mudra: 'Añjali (prostration mudrā — hands together in reverence)',
    rightHandAttribute: 'Prostration — palms together at crown in homage',
    leftHandAttribute: 'The merit of 88 Buddhas accumulated across three kalpas',
    pureLand: 'The field of merit of 88 awakened beings across three kalpas',
    element: 'Earth',
    chakra: 'root',
    frequencyHz: 396,
    emissionColor: '#fde68a',
    vowEssence: 'Great repentance and purification through homage to 88 Buddhas',
  },
};

export function getDeityVisualization(id: string): DeityVisualization | undefined {
  return DEITY_VISUALIZATIONS[id];
}
